[tool.poetry]
name = "lichess-opening-helper"
version = "0.1.0"
description = ""
authors = ["Arges42 <22573196+Arges42@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
